name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Give gradlew permission
      run: chmod +x android-client/gradlew

    - name: Build Debug APK
      run: ./android-client/gradlew :app:assembleDebug
      working-directory: android-client

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecureMsg-debug-apk
        path: android-client/app/build/outputs/apk/debug/app-debug.apk
