name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: Build Debug APK
      run: ./gradlew :android-client:assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: SecureMsg-debug-apk
        path: android-client/app/build/outputs/apk/debug/app-debug.apk
